[build]
  publish = "dist"
  command = "ng build --configuration production"

[functions]
  directory = "netlify-functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/ngsw.json"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "no-cache"

# (Opcional) Exemplo de cache agressivo para arquivos estáticos com hash no nome
[[headers]]
  for = "/*.@(js|css|woff2|png|jpg|jpeg|svg)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ========================
# Configuração de ambiente por branch
# ========================

# Ambiente para branch "dev"
[context.dev]
  command = "ng build --configuration development"

# Ambiente para branch "staging"
[context.staging]
  command = "ng build --configuration development"

# Ambiente para deploy preview (ex: Pull Request)
[context.deploy-preview]
  command = "ng build --configuration development"

# Ambiente local (usado com netlify dev)
[context.branch-deploy]
  command = "ng build --configuration development"

# Ambiente de produção (branch principal)
[context.production]
  environment = { NG_APP_API_URL = "https://api.meusite.com" }
